AD-84:Fixed width issue of ad sizes
wpeka/wpadcenter pull request #114
Opened 2021-04-14 05:30 UTC by pranayhbwsl

2021-04-14 06:46 UTC, dhananjaymayane commented on includes/class-wpadcenter-single-ad-widget.php
> +		if ( ! empty( $instance['max_width'] ) && 'on' === $instance['max_width'] ) {
check for undefined index notice

2021-04-14 06:48 UTC, dhananjaymayane requested changes
Please update the code for undefined index check also

2021-04-14 08:20 UTC, wpekaclub approved these changes

2021-04-15 05:01 UTC, dhananjaymayane approved these changes

2021-04-15 05:01 UTC, merged