Unit test
wpeka/wpadcenter pull request #144
Opened 2021-04-23 12:16 UTC by sonali-londhe

Added tests for admin class functions.

2021-04-23 12:33 UTC, sonali-londhe commented
Test cases for Admin class functions.

2021-04-23 12:57 UTC, sonali-londhe commented
Added test cases for admin class functions.

2021-04-26 04:59 UTC, dhananjaymayane requested changes
Please remove unnecessary code.

2021-04-26 05:52 UTC, dhananjaymayane approved these changes

2021-04-26 05:52 UTC, merged